name: neural-taxonomy
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libcxx=20.1.8
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.12.0
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - blis==1.3.3
      - catalogue==2.0.10
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - contourpy==1.3.2
      - cycler==0.12.1
      - cymem==2.0.13
      - datasets==4.4.2
      - dill==0.4.0
      - distro==1.9.0
      - docstring-parser==0.17.0
      - en-core-web-sm==3.8.0
      - exceptiongroup==1.3.1
      - faiss-cpu==1.13.2
      - filelock==3.20.2
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hdbscan==0.8.41
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - jsonlines==4.0.0
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - murmurhash==1.0.15
      - networkx==3.4.2
      - numpy==2.2.6
      - openai==2.14.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - preshed==3.0.12
      - propcache==0.4.1
      - psutil==7.2.1
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==5.2.0
      - six==1.17.0
      - smart-open==7.5.0
      - sniffio==1.3.1
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.2
      - sympy==1.14.0
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - tooldantic==0.1.0
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - wasabi==1.1.3
      - weasel==0.4.3
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /Users/dariosoatto/anaconda3/envs/neural-taxonomy
